'use client'

import { useSession } from 'next-auth/react'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/Button'

interface PetPass {
  id: string
  autoGeneratedCode: string
  petName: string
  species: string
  breed?: string
  createdAt: string
  metalTag?: {
    id: string
    status: string
  }
}

export default function DashboardPage() {
  const { data: session, status } = useSession()
  const [petPasses, setPetPasses] = useState<PetPass[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (session) {
      fetchPetPasses()
    }
  }, [session])

  const fetchPetPasses = async () => {
    try {
      const response = await fetch('/api/petpass')
      if (response.ok) {
        const data = await response.json()
        setPetPasses(data.petpasses)
      }
    } catch (error) {
      console.error('Error fetching pet passes:', error)
    } finally {
      setLoading(false)
    }
  }

  if (status === 'loading') {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Caricamento...</p>
        </div>
      </div>
    )
  }

  if (!session) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Accesso richiesto</h1>
          <p className="text-gray-600 mb-6">Devi essere autenticato per accedere alla dashboard.</p>
          <Link href="/login">
            <Button>Accedi</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">La tua Dashboard</h1>
          <p className="mt-2 text-gray-600">
            Benvenuto, {session.user?.email}! Gestisci i tuoi PetPass qui.
          </p>
        </div>

        <div className="mb-6">
          <Link href="/create-petpass">
            <Button size="lg">
              ✨ Crea un nuovo PetPass
            </Button>
          </Link>
        </div>

        {loading ? (
          <div className="text-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
            <p className="mt-4 text-gray-600">Caricamento PetPass...</p>
          </div>
        ) : petPasses.length === 0 ? (
          <div className="bg-white rounded-lg shadow p-8 text-center">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl">🐾</span>
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              Nessun PetPass creato
            </h3>
            <p className="text-gray-600 mb-6">
              Crea il primo PetPass per il tuo amico a quattro zampe!
            </p>
            <Link href="/create-petpass">
              <Button>Crea il primo PetPass</Button>
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {petPasses.map((petPass) => (
              <div key={petPass.id} className="bg-white rounded-lg shadow-md p-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-900">
                    {petPass.petName}
                  </h3>
                  <span className="text-sm text-gray-500">
                    {petPass.species}
                  </span>
                </div>
                
                <div className="space-y-2 mb-4">
                  <p className="text-sm text-gray-600">
                    <strong>Codice:</strong> {petPass.autoGeneratedCode}
                  </p>
                  {petPass.breed && (
                    <p className="text-sm text-gray-600">
                      <strong>Razza:</strong> {petPass.breed}
                    </p>
                  )}
                  <p className="text-sm text-gray-600">
                    <strong>Creato:</strong> {new Date(petPass.createdAt).toLocaleDateString('it-IT')}
                  </p>
                </div>

                <div className="flex flex-col space-y-2">
                  <Link href={`/petpass/${petPass.autoGeneratedCode}`}>
                    <Button variant="secondary" className="w-full" size="sm">
                      Visualizza PetPass
                    </Button>
                  </Link>
                  <Link href={`/edit-petpass/${petPass.autoGeneratedCode}`}>
                    <Button variant="ghost" className="w-full" size="sm">
                      Modifica
                    </Button>
                  </Link>
                  {!petPass.metalTag && (
                    <Button variant="primary" className="w-full" size="sm">
                      Ordina Tag Metallico (€19.99)
                    </Button>
                  )}
                  {petPass.metalTag && (
                    <div className="text-sm text-center py-2 bg-green-50 rounded border">
                      Tag Metallico: {petPass.metalTag.status}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Subscription Info */}
        <div className="mt-12 bg-white rounded-lg shadow p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Il tuo Piano
          </h2>
          <div className="flex items-center justify-between">
            <div>
              <p className="text-gray-600">Piano Free</p>
              <p className="text-sm text-gray-500">
                Puoi creare fino a 1 PetPass gratuito
              </p>
            </div>
            <Link href="/pricing">
              <Button variant="primary">
                Aggiorna Piano
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
} 